# Generated by Django 5.0.6 on 2024-07-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='account_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='after_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
