# Generated by Django 5.0.6 on 2024-07-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transectionmodel',
            name='balance',
        ),
        migrations.AlterField(
            model_name='transectionmodel',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
