# Generated by Django 5.0.6 on 2024-07-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_remove_transectionmodel_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transectionmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
