# Generated by Django 5.0.6 on 2024-07-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('book_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='book_category',
            field=models.ManyToManyField(to='book_category.bookcategorymodel'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
