# Generated by Django 5.0.6 on 2024-07-06 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('book', '0002_bookmodel_book_category_alter_bookmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountmodel'),
        ),
    ]
