# Generated by Django 5.0.6 on 2024-07-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_bookmodel_user_bookmodel_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(upload_to='book/media/uploads/'),
        ),
    ]
