# Generated by Django 5.0.6 on 2024-07-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_bookmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
