# Generated by Django 5.0.6 on 2024-07-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_reviewmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewModel',
        ),
    ]
