# Generated by Django 5.0.6 on 2024-07-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepositForm',
        ),
    ]
