# Generated by Django 5.0.6 on 2024-07-07 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountmodel_user'),
        ('borrow_book', '0002_delete_depositform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowmodel',
            name='account',
        ),
        migrations.AlterField(
            model_name='borrowmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='accounts.accountmodel'),
        ),
    ]
