# Generated by Django 5.0.6 on 2024-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0005_transectionmodel_delete_borrowmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transectionmodel',
            name='book',
        ),
        migrations.AddField(
            model_name='transectionmodel',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('deposit', 'deposit')], max_length=50, null=True),
        ),
    ]
