# Generated by Django 5.0.6 on 2024-07-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0007_alter_transectionmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transectionmodel',
            name='amount',
        ),
        migrations.AddField(
            model_name='transectionmodel',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
