# Generated by Django 5.0.6 on 2024-07-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0010_alter_transectionmodel_transaction_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransectionModel',
        ),
    ]
