# Generated by Django 5.0.6 on 2024-07-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbookmodel',
            name='book',
        ),
    ]
