# Generated by Django 5.0.6 on 2024-07-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_bookmodel_account_bookmodel_user'),
        ('borrow_book', '0013_remove_borrowbookmodel_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbookmodel',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, to='book.bookmodel'),
        ),
    ]
