# Generated by Django 5.0.6 on 2024-07-08 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_bookmodel_account_bookmodel_user'),
        ('borrow_book', '0014_borrowbookmodel_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbookmodel',
            name='book',
        ),
        migrations.AddField(
            model_name='borrowbookmodel',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.bookmodel'),
        ),
    ]
